services:
  mysql:
    image: 'mysql:8.0.34'
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - "3306:3306"
